import Link from "next/link";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <ul>
                    <li>
                        <Link href="/">Home</Link>
                    </li>
                    <li>
                        <Link href="/api/auth/signout">Sign Out</Link>
                    </li>
                </ul>
                {children}
            </body>
        </html>
    );
}
